name: time series update schedule script

on:
  push:
    branches: main
  schedule:
  - cron: "21 19 * * *"

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        run: r-lib/actions/setup-r@v3
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v3
        with:
          packages: |
            any::tidyverse
            any::lubridate
            any::httr
            
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Run R script
        run: Rscript crabsst_update.R
        
      - name: Commit files
        run: |
          git config --local user.name MattCallahan-NOAA
          git config --local user.email matt.callahan@noaa.gov
          git add --all
          git commit -am "GH ACTION Headlines $(date)"
          git push origin || echo "No changes to commit"

