name: time series update schedule script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
  - cron: "08 19 * * *"



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 
        
      - name: Setup R
        run: apt install r-base
        
      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("tidyverse", "httr", "lubridate")'
        
      - name: Run R script
        run: Rscript crabsst_update.R
        
      - name: Commit files
        run: |
          git config --local user.name MattCallahan-NOAA
          git config --local user.email matt.callahan@noaa.gov
          git add --all
          git commit -am "GH ACTION Headlines $(date)"
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
